const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{JSDOM,VirtualConsole}=require('jsdom');
const root=path.resolve(__dirname,'..'),KEY='stage11-writing-studio-v3';
function setup(hash='#home',saved){
 const errors=[],vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e.message));const dom=new JSDOM(fs.readFileSync(path.join(root,'index.html'),'utf8'),{url:'https://studio.test/'+hash,runScripts:'outside-only',virtualConsole:vc});const w=dom.window,doc=w.document,events=new WeakMap(),blobs=[],clipboard=[],clock={now:Date.now()},ticks=[];
 const add=w.EventTarget.prototype.addEventListener;w.EventTarget.prototype.addEventListener=function(kind,fn,opts){events.set(this,[...(events.get(this)||[]),kind]);return add.call(this,kind,fn,opts);};
 w.scrollTo=()=>{};w.Element.prototype.scrollIntoView=()=>{};w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(value=''){this.returnValue=value;this.open=false;this.dispatchEvent(new w.Event('close'));};w.Blob=Blob;w.URL.createObjectURL=b=>{blobs.push(b);return 'blob:export-'+blobs.length;};w.URL.revokeObjectURL=()=>{};Object.defineProperty(w.navigator,'clipboard',{value:{writeText:async t=>clipboard.push(t)}});w.Date.now=()=>clock.now;w.setInterval=fn=>{ticks.push(fn);return 1;};w.setTimeout=fn=>{fn();return 1;};w.print=()=>{w.printed=(w.printed||0)+1;assert(doc.body.classList.contains('printing-record'));};
 if(saved)w.localStorage.setItem(KEY,JSON.stringify(saved));for(const file of ['curriculum.js','engine.js','app.js'])w.eval(fs.readFileSync(path.join(root,'assets',file),'utf8'));
 const api={w,doc,errors,events,blobs,clipboard,clock,ticks,el:id=>doc.getElementById(id),state:()=>JSON.parse(w.localStorage.getItem(KEY)),click:id=>{assert(api.el(id),id);api.el(id).click();assert.deepEqual(errors,[]);},input:(id,value,type='input')=>{const el=api.el(id);assert(el,id);if(el.type==='checkbox')el.checked=value;else el.value=value;el.dispatchEvent(new w.Event(type,{bubbles:true}));assert.deepEqual(errors,[]);},route:hash=>{w.history.replaceState(null,'',hash);w.dispatchEvent(new w.HashChangeEvent('hashchange'));assert(doc.querySelector('main h1'),hash);assert.deepEqual(errors,[]);},confirm:value=>{api.el('confirmDialog').close(value);assert.deepEqual(errors,[]);},close:()=>w.close()};return api;
}
test('All pages, genres and pathways render with bound CTA controls and valid destinations',()=>{
 const a=setup(),D=a.w.STUDIO_DATA;let views=0,links=0;for(const genre of Object.keys(D.genres))for(const pathway of ['foundation','core','challenge'])for(const page of ['home','tasks','review','plan','vocabulary','practice','develop','draft','progress','reference','teacher']){a.input('genre',genre,'change');a.input('pathway',pathway,'change');a.route('#'+page);views++;const ids=[...a.doc.querySelectorAll('[id]')].map(x=>x.id);assert.equal(new Set(ids).size,ids.length,`${genre}/${page}: duplicate ID`);for(const b of a.doc.querySelectorAll('main button'))assert((a.events.get(b)||[]).includes('click'),`${page}: unbound ${b.id||b.textContent}`);for(const link of a.doc.querySelectorAll('main a')){const href=link.getAttribute('href');assert(href?.startsWith('#'));assert(['home','tasks','review','plan','vocabulary','practice','develop','draft','progress','reference','teacher'].includes(href.slice(1).split('?')[0]));links++;}assert(a.w.STUDIO_ENGINE.validateState(a.state()));}assert.equal(views,396);assert(links>1000);a.close();
});
test('All 52 task links select the right task and keep separate saved drafts',()=>{
 const a=setup('#tasks'),D=a.w.STUDIO_DATA;for(const [g,genre]of Object.entries(D.genres))for(const p of genre.prompts){a.route('#draft?task='+p.id);assert.equal(a.state().settings.genre,g);assert.equal(a.state().settings.unit,genre.unitId);a.input('draftText','Test draft for '+p.id);a.route('#plan?task='+p.id);a.input('planFocus','Focus for '+p.id);a.route('#draft?task='+p.id);assert.equal(a.el('draftText').value,'Test draft for '+p.id);}assert.equal(Object.values(a.state().drafts).filter(d=>d.text).length,52);a.close();
});
test('Vocabulary CTAs validate, reveal support, check transfer, retry, navigate and reset one word',()=>{
 const a=setup('#vocabulary');a.click('revealVocab');assert(a.el('vocabValidation').textContent.includes('prediction'));a.click('vocabHint');assert(!a.el('vocabHintText').hidden);a.input('vocabPrediction','My meaning');a.input('vocabClue','A context clue');a.click('revealVocab');assert(a.el('vocabOwn'));a.click('checkTransfer');assert(a.el('vocabValidation').textContent.includes('Choose'));const options=a.doc.querySelectorAll('[name=vocabTransfer]');options[0].checked=true;options[0].dispatchEvent(new a.w.Event('change'));a.click('checkTransfer');assert(a.el('checkTransfer').disabled);a.click('retryTransfer');assert(!a.el('checkTransfer').disabled);a.input('vocabOwn','My own sentence');a.click('resetVocab');a.confirm('cancel');assert.equal(a.el('vocabOwn').value,'My own sentence');a.click('resetVocab');a.confirm('confirm');assert(!a.el('vocabOwn'));a.click('supportVocab');assert(a.el('vocabOwn'));a.click('definitionList');assert(!a.el('definitionTable').hidden);a.click('definitionList');assert(a.el('definitionTable').hidden);a.click('nextWord');a.click('prevWord');a.click('shuffleWord');assert(!a.el('prevWord').disabled);a.doc.querySelector('[data-word="0"]').click();assert(a.el('prevWord').disabled);const choice=a.doc.querySelector('[data-phrase][data-natural="1"]');choice.click();assert(a.doc.querySelector('[data-reset-phrase]'));a.doc.querySelector('[data-reset-phrase]').click();a.close();
});
test('Focus practice CTAs handle every item type, locked checks, chunks, hints and scoped reset',()=>{
 const a=setup('#practice');a.input('genre','essay','change');a.click('checkAnswer');assert(a.el('practiceValidation').textContent.includes('Unanswered'));a.click('showHint');assert(!a.el('practiceHint').hidden);const bank=a.w.STUDIO_ENGINE.makeBank('essay','foundation');for(let i=0;i<bank.length;i++){a.input('questionSelect',String(i),'change');const q=bank[i];if(a.el('practiceText'))a.input('practiceText',q.answers[0]);else{const opt=[...a.doc.querySelectorAll('[name=practiceAnswer]')].find(x=>x.value===q.answers[0]);opt.checked=true;opt.dispatchEvent(new a.w.Event('change'));}a.click('checkAnswer');assert(a.el('checkAnswer').disabled);assert(a.state().answers[q.id].firstCorrect);a.click('tryAgain');a.click('clearAnswer');if(q.kind==='order'){a.doc.querySelector('[data-chunk]').click();a.click('undoChunk');a.doc.querySelector('[data-chunk]').click();a.click('clearChunks');}a.click('resetActivity');assert(!a.state().answers[q.id]);}a.click('prevQuestion');a.click('nextQuestion');a.close();
});
test('Review quiz CTAs gate meanings, preserve first score and reset only the selected record',()=>{
 const a=setup('#review');a.input('reviewUnit','u9','change');assert(a.el('checkReview').disabled);a.click('submitReviewPrediction');assert(a.el('reviewStatus').textContent.includes('prediction'));a.input('reviewPrediction','Prediction');a.input('reviewClue','Clue');a.click('submitReviewPrediction');assert(!a.el('checkReview').disabled);a.click('checkReview');assert(a.el('reviewStatus').textContent.includes('Choose'));a.click('hintReview');const opt=a.doc.querySelector('[name=reviewAnswer]');opt.checked=true;opt.dispatchEvent(new a.w.Event('change'));a.click('checkReview');const first=a.state().answers['review-vocabulary-u9-0'].firstCorrect;a.click('retryReview');const other=a.doc.querySelectorAll('[name=reviewAnswer]')[1];other.checked=true;other.dispatchEvent(new a.w.Event('change'));a.click('checkReview');assert.equal(a.state().answers['review-vocabulary-u9-0'].firstCorrect,first);a.click('resetReview');a.confirm('cancel');assert(a.state().answers['review-vocabulary-u9-0']);a.click('resetReview');a.confirm('confirm');assert(!a.state().answers['review-vocabulary-u9-0']);a.click('nextReview');a.click('supportReview');a.click('previousReview');for(const mode of ['linkers','writing']){a.input('reviewMode',mode,'change');a.click('hintReview');const r=a.doc.querySelector('[name=reviewAnswer]');r.checked=true;r.dispatchEvent(new a.w.Event('change'));a.click('checkReview');assert(a.el('checkReview').disabled);}a.route('#review?unit=u4&mode=vocabulary');assert.equal(a.el('reviewMode').value,'vocabulary');a.close();
});
test('Draft, development, timer, revision, clipboard and export CTAs preserve actual work',async()=>{
 const a=setup('#draft?task=essay-1');a.input('genre','essay','change');const id=a.state().settings.prompt||a.w.STUDIO_DATA.genres.essay.prompts[0].id;a.click('analyse');assert(a.doc.querySelector('#writingFeedback').textContent.includes('No writing submitted'));a.input('draftText','Students helps at a shelter.');a.click('analyse');assert.equal(a.state().drafts[id].versions.length,1);a.input('draftText','Students help at a shelter.');assert(!a.el('feedbackFreshness').hidden);a.click('analyse');assert(a.el('feedbackFreshness').hidden);a.click('analyse');assert.equal(a.state().drafts[id].versions.length,2);a.input('independent',true,'change');assert(a.el('draftSupport').hidden);a.input('timerMinutes','1');a.click('timerStart');assert(a.state().timer.running);a.clock.now+=61000;a.ticks.forEach(f=>f());assert.equal(a.state().timer.remaining,0);assert(!a.el('draftText').disabled);a.click('timerStart');a.click('timerStart');assert(!a.state().timer.running);a.click('timerReset');assert.equal(a.state().timer.remaining,60);a.input('untimed',true,'change');a.click('timerStart');assert(!a.state().timer.running);a.input('timerMinutes','0','change');assert.equal(a.el('timerMinutes').value,'1');a.click('copyDraft');await Promise.resolve();assert(a.clipboard.includes('Students help at a shelter.'));a.doc.querySelector('[data-copy-version]').click();await Promise.resolve();assert(a.clipboard.length>=2);a.click('downloadDraft');assert(a.el('exportDialog').open);assert.equal(await a.blobs.at(-1).text(),'Students help at a shelter.');a.click('selectExport');a.click('closeExport');a.click('clearDraft');a.confirm('cancel');assert(a.el('draftText').value);a.route('#develop');a.input('develop-paragraph','Students helps at a shelter.');a.click('developReview');assert(a.el('developFeedback').textContent.includes('Students helps'));a.click('clearDevelop');a.confirm('confirm');assert.equal(a.el('develop-paragraph').value,'');a.route('#draft');assert(a.el('draftText').value);a.close();
});
test('Progress backup/restore, malformed input, newer draft protection, print and complete reset work',async()=>{
 const a=setup('#draft');a.input('genre','essay','change');a.input('draftText','My saved draft.');a.route('#progress');a.input('reflect-strength','My reflection');a.click('participation');assert(a.el('printRecord'));a.click('printRecord');assert.equal(a.w.printed,1);assert(!a.doc.body.classList.contains('printing-record'));a.click('backup');const exported=a.el('exportText').value;assert(JSON.parse(exported).drafts);a.click('closeExport');a.click('exportAll');a.click('closeExport');a.click('exportReport');assert(a.el('exportText').value.includes('My saved draft')===false);assert(a.el('exportText').value.includes('submitted versions'));a.click('closeExport');a.input('pasteBackup','invalid');a.click('restorePasted');assert(a.el('importStatus').textContent.includes('not restored'));a.input('pasteBackup',exported);a.click('restorePasted');assert(a.el('importStatus').textContent.includes('restored'));const older=JSON.parse(exported),key=Object.keys(older.drafts)[0];older.drafts[key].text='Older imported text';older.drafts[key].updatedAt=0;a.input('pasteBackup',JSON.stringify(older));a.click('restorePasted');assert.equal(a.state().drafts[key].text,'My saved draft.');Object.defineProperty(a.el('importBackup'),'files',{configurable:true,value:[{size:20,text:async()=>exported}]});a.el('importBackup').dispatchEvent(new a.w.Event('change'));await new Promise(r=>setImmediate(r));assert(a.el('importStatus').textContent.includes('restored'));a.click('clearAll');a.confirm('cancel');assert(Object.keys(a.state().drafts).length);a.click('clearAll');a.confirm('confirm');assert.equal(Object.keys(a.state().drafts).length,0);assert.equal(a.state().settings.genre,'essay');assert(a.w.STUDIO_ENGINE.validateState(a.state()));a.close();
});
test('Navigation cancels destructive confirmation and imported empty chunk records do not crash',()=>{
 const E=require('../assets/engine.js'),saved=E.defaultState();saved.answers['essay-foundation-order-1']={value:'',checked:false};const a=setup('#practice?question=13',saved);a.click('checkAnswer');assert(a.el('practiceValidation').textContent.includes('Unanswered'));a.route('#draft');a.input('draftText','Keep this test draft.');a.click('clearDraft');assert(a.el('confirmDialog').open);a.route('#plan');assert(!a.el('confirmDialog').open);assert(Object.values(a.state().drafts).some(d=>d.text==='Keep this test draft.'));a.close();
});
