const test=require('node:test'),assert=require('node:assert/strict'),E=require('../assets/engine.js');
global.window={};require('../assets/curriculum.js');const D=window.STUDIO_DATA;
const cases={developed:'Students should be able to choose suitable volunteering roles because practical responsibility can develop patience. For example, a reading mentor may explain an unfamiliar word several times to a younger pupil. Adapting the explanation requires the mentor to listen carefully rather than repeat the same instruction. This shows how a suitable role can create an opportunity to practise patience, supporting a policy that offers meaningful choices.',underdeveloped:'Volunteering is good. It helps people. Schools should do it.',offtopic:'My favourite meal is vegetable soup. I enjoy cooking it with my family on Sundays.',short:'It is good.',empty:'',spam:Array(30).fill('banana').join(' ')};
test('All six routes provide 90 keyed, explained checkpoints',()=>{const ids=new Set();for(const g of ['essay','biography'])for(const p of ['foundation','core','challenge']){const bank=E.makeBank(g,p);assert.equal(bank.length,15);for(const q of bank){assert(!ids.has(q.id));ids.add(q.id);assert(q.explanation&&q.hint&&q.stem);for(const a of q.answers)assert(E.answerMatches(a.toUpperCase()+' ',q.answers));if(q.options)assert(q.options.includes(q.answers[0]));}assert.equal(bank.filter(q=>q.kind==='linker').length,5);}assert.equal(ids.size,90);});
test('Every vocabulary entry has two contexts, natural phrases and clue evidence',()=>{let count=0;for(const u of D.units)for(const v of u.vocab){count++;assert(v.transfer&&v.e&&v.transfer!==v.e);assert(v.collocations.length>=2);assert(v.evidence&&v.clueExplanation);assert(v.transfer.includes(v.evidence));}assert.equal(count,150);});
test('Feedback responds to passage evidence without assigning grades',()=>{for(const [name,text]of Object.entries(cases)){const a=E.analyseWriting(text,'essay','Offer suitable volunteering choices','Should schools require volunteering?');assert(!('score'in a));assert(!('grade'in a));assert(a.priorities.length<=3);for(const x of [...a.observations,...a.priorities,...a.checks])assert(text.includes(x.quote.replace(/…$/,'')),`${name}: actual quote`);if(name==='empty')assert.equal(a.checks.length,0);if(['short','underdeveloped','offtopic'].includes(name))assert(a.insufficient.some(x=>x.includes('short passage')));if(name==='offtopic')assert(a.insufficient.some(x=>x.includes('may be off-topic')));if(name==='spam')assert(a.priorities.some(x=>x.id==='repetition'));if(name==='developed'){assert.equal(a.priorities.length,0);assert(a.observations.some(x=>x.title==='Example-signalling phrase'));assert(a.insufficient.some(x=>x.includes('cannot determine')));}}});
test('Specific local edits preserve surrounding text and map to standards',()=>{const text="Students helps at a shelter. They do a impact on the community. I can't attend every week.";const a=E.analyseWriting(text,'essay','Support local communities','Volunteering');assert.equal(a.priorities.length,3);assert.equal(a.priorities[0].revision,'Students help at a shelter.');assert.equal(a.priorities[1].revision,'They make an impact on the community.');assert.equal(a.priorities[2].revision,'I cannot attend every week.');assert.equal(a.priorities[0].criterion,'UO 2.h.d');const b=E.analyseWriting('She have a plan.','biography','perseverance','Biography');assert.equal(b.priorities[0].criterion,'UO 1.g.d');assert(!E.analyseWriting('Does she have a plan?','biography','','').priorities.some(x=>x.id==='grammar'));});
test('Version comparison reports pattern changes, never semantic improvement',()=>{const old={text:'Students helps at a shelter.',analysis:E.analyseWriting('Students helps at a shelter.','essay','','')},next={text:'Students help at a shelter.',analysis:E.analyseWriting('Students help at a shelter.','essay','','')};const c=E.compareVersions(old,next);assert.equal(c.changed,true);assert(c.removed.includes('Check this agreement pattern'));assert(c.note.includes('do not establish'));assert.equal(E.compareVersions(next,next).changed,false);});
test('Accepted alternatives and typography are handled',()=>{assert(E.answerMatches(' HAD COLLECTED. ',['had collected']));assert(E.answerMatches('student’s work',["student's work"]));const q=E.makeBank('biography','foundation').find(x=>x.kind==='order');assert(E.answerMatches('Before the club opened, Maya had collected books.',q.answers));assert(!E.answerMatches('banana',q.answers));});
test('Backups reject malformed state and protect recovery',()=>{const s=E.defaultState();assert(E.validateState(s));for(const change of [x=>x.plans={bad:4},x=>x.answers={bad:{chunks:'oops'}},x=>x.timer.minutes=0,x=>x.timer.running=true,x=>x.settings.unit=null,x=>x.visited={draft:1},x=>x.drafts={bad:{text:'x',versions:[],review:{},independent:false}}]){const x=JSON.parse(JSON.stringify(s));change(x);assert.equal(E.validateState(x),false);}assert(!E.validateState(JSON.parse('{"schema":3,"__proto__":{}}')));const valid=E.defaultState();const a=E.analyseWriting(cases.developed,'essay','','');valid.drafts.task={text:cases.developed,versions:[{text:cases.developed,date:Date.now(),analysis:a}],review:{focus:'My reflection'},independent:false,updatedAt:Date.now(),feedback:a};assert(E.validateState(valid));});

test('Every covered unit has active writing tasks; all reference prompts survive',()=>{
 const genres=Object.values(D.genres),prompts=genres.flatMap(g=>g.prompts);
 assert.equal(prompts.length,52);assert.equal(new Set(prompts.map(p=>p.id)).size,52);
 for(const unit of D.units)assert.ok(genres.some(g=>g.unitId===unit.id&&g.prompts.length),unit.id);
 for(const task of [...D.referenceTasks,...D.legacyTasks])for(const prompt of task.prompts)assert.ok(prompts.some(p=>p.text===prompt),prompt);
 for(const genre of Object.keys(D.genres)){const state=E.defaultState();state.settings.genre=genre;assert.equal(E.validateState(state),true,genre);}
});
test('Informal letter feedback accepts contractions and uses genre criteria',()=>{
 const text="Hi Linh! I'm feeling better now. I can't wait to see you. Students helps at the clinic.";
 const letter=E.analyseWriting(text,'letter','recovery','Write to a friend about recovery');
 assert.ok(!letter.priorities.some(p=>p.id==='register'));
 assert.ok(letter.priorities.some(p=>p.id==='grammar'));
 assert.ok(letter.priorities.every(p=>p.criterion.startsWith('Genre self-review')));
 assert.ok(letter.checks.every(p=>!p.question.includes('admirable quality')));
 assert.ok(E.analyseWriting(text,'essay','','').priorities.some(p=>p.id==='register'));
});
